---
title: "Helper File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Dataset/Investigate

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

#load in the dataset
loan_df <- read.csv('prosperLoanData.csv')

names(loan_df)
```

```{r}
head(loan_df)
```

```{r}
#subset data to the variables of interest
loan_df_subset <- subset(loan_df, select = c('ListingNumber', 'ListingCreationDate', 'CreditGrade', 'ProsperRating..Alpha.',
                                             'Term', 'LoanStatus', 'ClosedDate', 'BorrowerAPR', 'BorrowerRate', 'LenderYield',
                                             'ProsperScore', 'Occupation', 'EmploymentStatus', 'CreditScoreRangeLower',
                                             'CreditScoreRangeUpper', 'OpenRevolvingMonthlyPayment', 
                                             'BankcardUtilization', 'AvailableBankcardCredit', 'IncomeRange',
                                             'DebtToIncomeRatio', 'StatedMonthlyIncome', 'IncomeVerifiable'))
head(loan_df_subset)
```

```{r}
#write subsetted data.frame to a new csv to work from in the main project 
write.csv(loan_df_subset, file = 'loan_df_subset.csv')
```

```{r}
#general exploratory plot
ggplot(aes(x=Term), data = loan_df_subset) +
    geom_histogram()

```


```{r}
head(loan_df_subset)
```


```{r fig.height = 5, fig.width = 7}
#testing different parameters
ggplot(aes(x=LoanStatus), data = loan_df_subset) +
    geom_bar() +
    #rotate x axis labels 90 degrees
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
#to prevent code from showing, enter ^ those commands
ggplot(aes(x=BorrowerAPR), data = loan_df_subset) +
    geom_histogram()
```


```{r}
ggplot(aes(x = EmploymentStatus), data = loan_df_subset) +
    geom_histogram(stat = 'count')
```


```{r}
summary(loan_df_subset$ListingCreationDate)
```






